### ISSUE TITLE
sfud_init Returns 1 (Not Found)

### ISSUE THREAD

**Issue by bradocchs** [Seeed-Studio/Seeed_Arduino_SFUD#4]
No matter which example I try, it never gets past sfud_init because it never returns 0 (Success).

Using XIAO nRF52840 Sense board and trying to utilize the onboard 2MB of flash.

Any ideas? Thanks!

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by bradocchs** [comment]
I was able to get another library to work, so I don't know if it's still a problem or not. As far as I'm concerned you can close this issue.

**Comment by Lesords** [comment]
OK, I will close this issue. 

If you have other questions, you are welcome to reopen it.
